title: 'Logia Wolfgang Amadeus Mozart – Nº 1740, Montreal'
default_lang: es
author:
  name: 'Henry Pelaez Barban'
  email: henry.pelaez24@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
